### ISSUE TITLE
[! ] 程序出现错误,已停止 

### ISSUE THREAD

**Issue by yichensec** [Zh9ng9/everythingToExcel#1]
[! ] 程序出现错误,已停止
Traceback (most recent call last):
File "everythingToExcel.py", line 118, in main
data = EholeJsonData()
File "everythingToExcel.py", line 32, in EholeJsonData
ip_result = socket. getaddrinfo(hostname[:-1], 'http')
File "F:\python\lib\socket.py", line 914, in getaddrinfo
for res in _socket. getaddrinfo(host, port, family, type, proto, flags):
socket. gaierror: [Errno 11001] getaddrinfo failed

你好，这个问题如何去修复呢，在使用ehole工具常见到这个，然后就报错，麻烦作者百忙之中能给解惑，谢谢

**Comment by Zh9ng9** [comment]
请使用最新版本的脚本，若仍出现该问题，可使用不需要socket库的版本[everythingToExcel-nosocket.py](https://github.com/Zh9ng9/everythingToExcel/blob/master/everythingToExcel-nosocket.py)。

**Comment by Zh9ng9** [comment]
请尝试使用最新版本的脚本，若仍出现该问题，可使用不需要socket库的版本[everythingToExcel-nosocket.py](https://github.com/Zh9ng9/everythingToExcel/blob/master/everythingToExcel-nosocket.py)。
